flags: {}
packages:
- '.'
- '../gl-pal'
- '../glfw-pal'
- '../vr-pal'
- '../hydra-hs'
- '../halive'
- '../linear-extra'
- '../lens-extra'
- '../openvr-hs'
- '../freetype-gl-mini'
- '../tinyrick'
- '../bindings-GLFW'
resolver: nightly-2015-12-03
